- id: 200
  key: satoshi
  currency: btc
  fixed: 8
  fee: 0.0005
  inuse: true
  type: WithdrawChannelSatoshi
- id: 400
  key: bank
  currency: cny
  fixed: 2
  fee_max: 0
  min: 100
  max: 50000
  fee: 0.003
  proportion: true
  inuse: true
  type: WithdrawChannelBank
- id: 500
  key: ether
  currency: eth
  min_confirm: 1
  max_confirm: 6
  inuse: true
  fixed: 8
  fee: 0.0005
  type: WithdrawChannelEthereum
- id: 700
  key: litecoin
  currency: ltc
  min_confirm: 1
  max_confirm: 6
  inuse: true
  fixed: 8
  fee: 0.0003
  type: WithdrawChannelLitecoin
- id: 800
  key: dogecoin
  currency: doge
  min_confirm: 1
  max_confirm: 6
  inuse: true
  fixed: 8
  fee: 0.0003
  type: WithdrawChannelDogecoin
- id: 900
  key: dash
  currency: dash
  min_confirm: 1
  max_confirm: 6
  inuse: true
  fixed: 8
  fee: 0.0003
  type: WithdrawChannelDash
- id: 1000
  key: riecoin
  currency: ric
  min_confirm: 1
  max_confirm: 6
  inuse: true
  fixed: 8
  fee: 0.0003
  type: WithdrawChannelRiecoin
- id: 1100
  key: peercoin
  currency: ppc
  min_confirm: 1
  max_confirm: 6
  inuse: true
  fixed: 8
  fee: 0.0003
  type: WithdrawChannelPeercoin
- id: 1200
  key: primecoin
  currency: xpm
  min_confirm: 1
  max_confirm: 6
  inuse: true
  fixed: 8
  fee: 0.0003
  type: WithdrawChannelPrimecoin
- id: 1300
  key: florincoin
  currency: flo
  min_confirm: 1
  max_confirm: 6
  inuse: true
  fixed: 8
  fee: 0.0003
  type: WithdrawChannelFlorincoin
  